development:
  adapter: postgresql
  database: graphql_example_development
  encoding: utf8
  pool: 5

test:
  adapter: postgresql
  database: graphql_example_test
  encoding: utf8
  pool: 5
<% if ENV['DATABASE_URL'] %>
  url: <%= ENV['DATABASE_URL'] %>
<% end %>
